### ISSUE TITLE
Feature: Add args support for --workspace

### ISSUE THREAD

**Issue by litan1106** [xt0rted/dotnet-format#27]
Both a MSBuild project file and solution file found in XXX. Specify which to use with the --workspace option.

**Comment by xt0rted** [comment]
Hi @litan1106, sorry it took so long to see this. I'm working on an update that adds the `--folder` and `--workspace` options. It should be released later this week.

**Comment by xEoDx** [comment]
Hey! Any updates on this? I would like to use this github action but I need to specify the workspace, otherwise dotnet format fails.

Thanks!

**Comment by itabaiyu** [comment]
I'm also running into this same issue. Right now since I have everything in a `src` directory this Github action fails since `dotnet-format` can't find a project or solution file. Thanks in advance!

**Comment by victor-alcazar** [comment]
I tried to push a PR but it seems that it's not allowed. I forked the project and made some changes until the official repo adds this functionality. You can check it from here:
https://github.com/victor-alcazar/dotnet-format

**Comment by benoitdion** [comment]
@victor-alcazar thanks for sending this out. Looks like the `--project` option works well but doesn't look like it's compatible with `fail-fast: false` (always passes) or `dotnet-format-problem-matcher`. The two issues might be related.

**Comment by xt0rted** [comment]
Sorry for taking so long to get this fixed. I've been working on an update but as @benoitdion mentioned there's other issues that come up when using the `--project`/`--workspace` options that I'm trying to work around. There's also a v4 release that's about to come out which has a number of breaking changes related to this.

I think I have a fix that will work for this and the problem matcher. I need to do a bit more testing with it and hope to have an update out later this week for both actions.

Are any of you using the preview releases of `dotnet-format` v4?

**Comment by litan1106** [comment]
not yet, I am still using the pinned version in .config/dotnet-tool.json
`{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-format": {
      "version": "3.3.111304",
      "commands": [
        "dotnet-format"
      ]
    },
    "dotnet-reportgenerator-globaltool": {
      "version": "4.5.3",
      "commands": [
        "reportgenerator"
      ]
    },
    "dotnet-ef": {
      "version": "3.1.3",
      "commands": [
        "dotnet-ef"
      ]
    }
  }
}`

**Comment by feliwir** [comment]
How can i specify the workspace now? Why is this issue closed?
